part of 'settings_bloc.dart';

enum SettingStatus {
  INITIAL,
  ENABLE_LOCATION_SERVICE,
  OPEN_GPS_CONF_DLG,
  LOCATION_PERMISSION_DENIED,
  LOCATION_PERMISSION_DENIED_FOREVER,
  LOCATION_PERMISSION_WHILE_IN_USE,
  LOCATION_PERMISSION_ALWAYS
}

class SettingsState {}
